spring.application.name=ketokki-emoticon-maker

# MySQL 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/ketokki_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1111

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 파일 업로드 용량 설정
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=300MB

# 케토끼 파일 저장 경로
file.upload-dir=C:/dev/ketokki-sticker-maker/storage/uploads
file.converted-dir=C:/dev/ketokki-sticker-maker/storage/converted
file.zip-dir=C:/dev/ketokki-sticker-maker/storage/zips


# =========================
# File cleanup settings
# =========================

# 업로드/변환/ZIP 파일 보관 시간: 60분
file.cleanup.expire-minutes=60

# 자동 삭제 실행 주기: 10분마다 실행
file.cleanup.interval-millis=600000


# =========================
# Usage limit settings
# =========================

# 비회원 무료 체험 변환 횟수 제한: 하루 5회
usage.convert.daily-limit=5